#!/usr/bin/env python3
"""Generate and independently audit multi-user false-personalization probes."""
from __future__ import annotations

import argparse
import copy
from collections import Counter, defaultdict
from importlib import import_module
import json
import os
from pathlib import Path
from typing import Any

from api_client import write_json

_pipeline = import_module("04_generate_benchmark")
ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DATASET = ROOT / "runs_wxq" / "taskmaster_planning_defaults_v0_4"
REVISION = "false_personalization_probe_generation_v3_feedback_repair"
LABELS = {"A", "B", "C", "D"}

def read_jsonl(path: Path) -> list[dict[str, Any]]:
    return [json.loads(line) for line in path.open(encoding="utf-8") if line.strip()]

def call(args: argparse.Namespace, model: str, system: str, payload: dict[str, Any], max_tokens: int) -> dict[str, Any]:
    clone = copy.copy(args); clone.model = model
    return _pipeline.api_json(clone, system, payload, max_tokens)

def lifeline(sessions: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [{"session_id": s["session_id"], "session_index": s["session_index"], "timestamp": s["timestamp"], "messages":[{"role":m["role"],"content":m["content"]} for m in s["messages"]]} for s in sorted(sessions,key=lambda x:x["session_index"])]

def structural_error(row: dict[str, Any], valid_ids: set[str], episodes: dict[str, Any]) -> str | None:
    choices=row.get("choices",[]); ids=[x.get("choice_id") for x in choices if isinstance(x,dict)]
    if len(choices)!=4 or set(ids)!=LABELS or row.get("gold_choice_id") not in LABELS: return "invalid_choices"
    cited=list(dict.fromkeys(row.get("gold_evidence_session_ids",[])))
    if len(cited)<4 or not set(cited).issubset(valid_ids): return "invalid_evidence"
    if len({episodes[x] for x in cited})<3: return "evidence_not_three_episodes"
    lengths=[len(str(x.get("text","")).strip()) for x in choices]
    if min(lengths)<30 or max(lengths)>2.5*min(lengths): return "choice_length_leakage"
    return None

def main() -> None:
    p=argparse.ArgumentParser(); p.add_argument("--dataset",type=Path,default=DEFAULT_DATASET)
    p.add_argument("--base-url",default=os.getenv("HABITBENCH_BASE_URL") or os.getenv("OPENAI_BASE_URL")); p.add_argument("--api-key",default=os.getenv("HABITBENCH_API_KEY") or os.getenv("OPENAI_API_KEY"))
    p.add_argument("--generator-model",default="gpt-5.5"); p.add_argument("--audit-model",default="gpt-5.6-terra"); p.add_argument("--reasoning-effort",default="xhigh"); p.add_argument("--transport",default="curl_stream"); p.add_argument("--timeout",type=int,default=900); p.add_argument("--retries",type=int,default=4)
    p.add_argument("--controls", type=Path, default=None, help="Targeted, independently accepted controls; bypasses prior-shortfall selection.")
    p.add_argument(
        "--current-final-controls-only",
        action="store_true",
        help="Repair exactly the false-personalization controls currently released in private/probe_key.jsonl.",
    )
    p.add_argument(
        "--shortfall-report",
        type=Path,
        default=None,
        help="Restrict a repair pass to control IDs reported as shortfalls by a prior generation report.",
    )
    p.add_argument("--revision", default=REVISION, help="Cache and report namespace for a targeted repair pass.")
    args=p.parse_args()
    if not args.base_url or not args.api_key: raise SystemExit("Set HABITBENCH_BASE_URL and HABITBENCH_API_KEY")
    # Repair only controls still short after v2.  Earlier passes are retained as
    # frozen candidates and are never regenerated by this stage.
    if args.current_final_controls_only:
        published = read_jsonl(args.dataset / "private" / "probe_key.jsonl")
        controls = [
            row["negative_control"]
            for row in published
            if row.get("probe_type") == "false_personalization" and isinstance(row.get("negative_control"), dict)
        ]
        if len(controls) != 17 or len({row.get("control_id") for row in controls}) != 17:
            raise SystemExit("Expected exactly 17 unique released false-personalization controls")
    else:
        controls=read_jsonl(args.controls or (args.dataset/"private"/"false_personalization_controls_v1.jsonl"))
    prior=args.dataset/"reports"/"false_personalization_probe_generation_v2_repair.json"
    # A release-repair pass must cover every currently published control.  The
    # historical shortfall filter is only for the legacy incremental workflow.
    if args.controls is None and not args.current_final_controls_only and prior.exists():
        prior_shortfalls={r["user_id"]:{*r.get("shortfalls",[])} for r in json.loads(prior.read_text()).get("reports",[])}
        controls=[c for c in controls if c["control_id"] in prior_shortfalls.get(c["user_id"],set())]
    if args.shortfall_report is not None:
        shortfall_report = json.loads(args.shortfall_report.read_text(encoding="utf-8"))
        shortfalls = {
            control_id
            for report in shortfall_report.get("reports", [])
            for control_id in report.get("shortfalls", [])
        }
        controls = [control for control in controls if control.get("control_id") in shortfalls]
        if not controls:
            raise SystemExit("No controls matched --shortfall-report")
    by_user: dict[str,list[dict[str,Any]]]=defaultdict(list)
    for c in controls: by_user[c["user_id"]].append(c)
    sessions_by_user:dict[str,list[dict[str,Any]]]=defaultdict(list)
    for s in read_jsonl(args.dataset/"private"/"sessions_with_annotations.jsonl"): sessions_by_user[s["user_id"]].append(s)
    all_candidates=[]; reports=[]
    for user_id,user_controls in sorted(by_user.items()):
        # Give the generator the prior independent judgments, rather than asking
        # it to blindly repeat a formulation that leaked a generic answer.
        prior_rows=[]
        pg=args.dataset/"work"/"false_personalization"/"probe_generation_v2_repair"/f"{user_id}.json"
        pq=args.dataset/"work"/"false_personalization"/"probe_query_audit_v2_repair"/f"{user_id}.json"
        if pg.exists() and pq.exists():
            old=json.loads(pg.read_text()).get("probes",[])
            qa={x.get("candidate_id"):x for x in json.loads(pq.read_text()).get("answers",[]) if isinstance(x,dict)}
            ha={}
            for f in sorted((args.dataset/"work"/"false_personalization"/"probe_history_audit_v2_repair").glob(f"{user_id}_*.json")):
                ha.update({x.get("candidate_id"):x for x in json.loads(f.read_text()).get("answers",[]) if isinstance(x,dict)})
            wanted={c["control_id"] for c in user_controls}
            for row in old:
                cid=f"{row.get('control_id')}::{row.get('variant_id')}"
                if row.get("control_id") in wanted:
                    prior_rows.append({"control_id":row.get("control_id"),"query":row.get("query"),"choices":row.get("choices"),"proposed_gold":row.get("gold_choice_id"),"query_only_audit":qa.get(cid),"full_history_audit":ha.get(cid)})
        cache=args.dataset/"work"/"false_personalization"/f"probe_generation_{args.revision}"/f"{user_id}.json"
        if cache.exists(): raw=json.loads(cache.read_text())
        else:
            raw=call(args,args.generator_model,"You author difficult false-personalization travel-memory benchmark probes.",{
                "task":"Write exactly three replacement probes per control. The complete history should be necessary to reject a tempting but false stored personal default.","controls":user_controls,"prior_failed_attempts_and_independent_verdicts":prior_rows,
                "requirements":[
                    "Return {probes:[{control_id,variant_id,query,choices:[{choice_id,text}],gold_choice_id,gold_action,gold_evidence_session_ids,label_rationale,difficulty_rationale}]}",
                    "Each candidate has exactly four choices A/B/C/D. Every choice must be a short, concrete, equally actionable recommendation that satisfies the explicit trip constraints. Do not offer to ask a question, gather more information, compare options, wait, or decline.",
                    "Gold is one concrete context-matched action, not generic caution. Its wording must be no more conditional, comprehensive, safe, flexible, or polite than any distractor. At least two distractors must encode plausible fixed user defaults from the control.",
                    "Make the query underdetermined on its own: remove any price, duration, location, risk, convenience, or stated preference fact that would make one option ordinarily superior. Without user history, at least two choices should be equally reasonable concrete actions.",
                    "Do not make the locally rational answer obvious from a fixed-site venue, a single early meeting, parking price, walking distance, baggage amount, fare difference, or a stated itinerary constraint. Such cues made earlier false-personalization probes solvable without history.",
                    "Do not use a generic-safe distractor such as 'use rideshare', 'book the official hotel', 'take the nonstop', 'choose the closest airport', 'do not rent a car', or 'apply a case-by-case rule' when it is plainly supported by the query. All four actions must remain concretely viable on the query alone.",
                    "Make each choice 10 to 18 words, with no choice more than three words longer than another. Include the same level of concrete operational detail in every option; do not hide a policy explanation in only one choice.",
                    "Use the prior verdicts as hard negative feedback. Do not reuse their query framing, wording, or generic-best contrast. If an auditor previously picked one option without history, make the new four choices symmetric with respect to the reason it gave.",
                    "The full lifeline must uniquely make gold correct because it shows the alleged default is not stable and the current trip context selects gold. Do not include an 'always choose' versus 'consider context' contrast.",
                    "Use a fresh travel context and cite at least four supplied control evidence sessions from three episodes. Do not mention memory, benchmark, labels, or insufficient information.",
                ]},26000); write_json(cache,raw)
        valid_ids={s["session_id"] for s in sessions_by_user[user_id]}; episodes={s["session_id"]:s.get("memory_annotations",{}).get("episode_id") for s in sessions_by_user[user_id]}; control_by_id={c["control_id"]:c for c in user_controls}
        valid=[]; invalid={}
        for row in raw.get("probes",[]):
            if not isinstance(row,dict) or row.get("control_id") not in control_by_id: continue
            e=structural_error(row,valid_ids,episodes)
            cid=f"{row.get('control_id')}::{row.get('variant_id')}"
            if e: invalid[cid]=e; continue
            row=copy.deepcopy(row); row["candidate_id"]=cid; valid.append(row)
        # Query-only audit in one user batch.
        qcache=args.dataset/"work"/"false_personalization"/f"probe_query_audit_{args.revision}"/f"{user_id}.json"
        if qcache.exists(): qraw=json.loads(qcache.read_text())
        else:
            qraw=call(args,args.audit_model,"You independently audit whether travel-policy questions leak a unique answer without user history.",{"items":[{"candidate_id":r["candidate_id"],"query":r["query"],"choices":r["choices"]} for r in valid],"requirements":["Return {answers:[{candidate_id,choice_id,answerable_without_history,generic_best_exists,plausible_choice_ids,rationale}]}","Use only query and choices. A valid item requires choice_id=UNRESOLVED, answerable_without_history=false, generic_best_exists=false, and at least two plausible choices."]},9000); write_json(qcache,qraw)
        q={x.get("candidate_id"):x for x in qraw.get("answers",[]) if isinstance(x,dict)}
        # Complete-lifeline audit in batches of four candidates.
        h={}
        for start in range(0,len(valid),4):
            chunk=valid[start:start+4]; hcache=args.dataset/"work"/"false_personalization"/f"probe_history_audit_{args.revision}"/f"{user_id}_{start//4:03d}.json"
            if hcache.exists(): hraw=json.loads(hcache.read_text())
            else:
                hraw=call(args,args.audit_model,"You independently audit false-personalization decisions from complete raw user lifelines.",{"complete_raw_lifeline":lifeline(sessions_by_user[user_id]),"items":[{"candidate_id":r["candidate_id"],"query":r["query"],"choices":r["choices"]} for r in chunk],"requirements":["No habit graph, controls, labels, or proposed answer is available.","Return {answers:[{candidate_id,choice_id,ambiguous,difficulty,stable_preference_supported,evidence_session_ids,rationale}]}","Select the calibrated action only if history does not support a fixed preference on the tested dimension. stable_preference_supported must be false; difficulty must be medium or hard."]},7000); write_json(hcache,hraw)
            h.update({x.get("candidate_id"):x for x in hraw.get("answers",[]) if isinstance(x,dict)})
        chosen={}; reasons={}
        for row in valid:
            qq,hh=q.get(row["candidate_id"],{}),h.get(row["candidate_id"],{})
            err=[]
            plausible=qq.get("plausible_choice_ids",[])
            if qq.get("choice_id")!="UNRESOLVED" or qq.get("answerable_without_history") is not False or qq.get("generic_best_exists") is not False or not isinstance(plausible,list) or len(set(plausible))<2 or row["gold_choice_id"] not in plausible: err.append("query_only_failure")
            if hh.get("choice_id")!=row["gold_choice_id"] or hh.get("ambiguous") is not False or hh.get("stable_preference_supported") is not False or hh.get("difficulty") not in {"medium","hard"}: err.append("history_failure")
            if err: reasons[row["candidate_id"]]=err; continue
            chosen.setdefault(row["control_id"],{"row":row,"query":qq,"history":hh})
        # A control may have one accepted variant and several rejected ones.
        # Keep the per-candidate status exact; downstream staging must never
        # treat all siblings as accepted merely because their control passed.
        selected_candidate_ids = {item["row"]["candidate_id"] for item in chosen.values()}
        all_candidates.extend({"user_id":user_id,"control_id":r["control_id"],"candidate_id":r["candidate_id"],"accepted":r["candidate_id"] in selected_candidate_ids,"errors":reasons.get(r["candidate_id"],[])} for r in valid)
        reports.append({"user_id":user_id,"control_count":len(user_controls),"valid_candidate_count":len(valid),"accepted_control_count":len(chosen),"shortfalls":sorted({c["control_id"] for c in user_controls}-set(chosen)),"structural_invalid":invalid})
        print(f"false_probe_progress {user_id} accepted={len(chosen)}/{len(user_controls)}",flush=True)
    status="pass" if all(r["accepted_control_count"]==r["control_count"] for r in reports) else "reject"
    write_json(args.dataset/"reports"/f"false_personalization_probe_generation_{args.revision}.json",{"status":status,"revision":args.revision,"reports":reports,"candidates":all_candidates})
    print(json.dumps({"status":status,"reports":reports},ensure_ascii=False,indent=2)); raise SystemExit(0 if status=="pass" else 1)
if __name__=="__main__": main()
