# Source this file on Lumia before running full official-method experiments.
#
# Example:
#   source ./scripts/lumia/lumia_env_example.sh

export HABITBENCH_PROJECT_ROOT="${HABITBENCH_PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
export HABITBENCH_LLM_MODEL="${HABITBENCH_LLM_MODEL:-/data1/public/hf/Qwen/Qwen3-8B}"
export HABITBENCH_SERVED_MODEL="${HABITBENCH_SERVED_MODEL:-habitbench-qwen3-8b}"
export HABITBENCH_EMBED_MODEL="${HABITBENCH_EMBED_MODEL:-/home/jmzhang/models/e5-base-v2}"
export HABITBENCH_EMBED_DIMS="${HABITBENCH_EMBED_DIMS:-768}"
export HABITBENCH_SECOM_EMBED_MODEL="${HABITBENCH_SECOM_EMBED_MODEL:-$HABITBENCH_EMBED_MODEL}"
export HABITBENCH_SECOM_COMPRESSOR="${HABITBENCH_SECOM_COMPRESSOR:-/home/jmzhang/models/llmlingua-2-xlm-roberta-large-meetingbank}"
export HABITBENCH_SERVER_CUDA_VISIBLE_DEVICES="${HABITBENCH_SERVER_CUDA_VISIBLE_DEVICES:-0}"
export HABITBENCH_METHOD_CUDA_VISIBLE_DEVICES="${HABITBENCH_METHOD_CUDA_VISIBLE_DEVICES:-0}"
export HABITBENCH_STRUCTURED_OUTPUT_MODE="${HABITBENCH_STRUCTURED_OUTPUT_MODE:-json_schema}"
export HABITBENCH_MAX_MODEL_LEN="${HABITBENCH_MAX_MODEL_LEN:-40960}"
export HABITBENCH_MEMORY_LLM_MAX_TOKENS="${HABITBENCH_MEMORY_LLM_MAX_TOKENS:-4096}"
export HABITBENCH_OFFICIAL_TIMEOUT_SEC="${HABITBENCH_OFFICIAL_TIMEOUT_SEC:-172800}"
export HABITBENCH_PROGRESS_EVERY="${HABITBENCH_PROGRESS_EVERY:-100}"

export OPENAI_API_KEY="${OPENAI_API_KEY:-dummy}"
export OPENAI_BASE_URL="${OPENAI_BASE_URL:-http://127.0.0.1:8000/v1}"
export PYTHON_BIN="${PYTHON_BIN:-/home/jmzhang/miniconda3/envs/habitbench-e2e/bin/python}"

export HABITBENCH_DATASET="${HABITBENCH_DATASET:-$HABITBENCH_PROJECT_ROOT/domain/food/food_habit_lifelines_stress}"
export HABITBENCH_RESULTS="${HABITBENCH_RESULTS:-$HABITBENCH_PROJECT_ROOT/results}"
